name: Update README with Latest Release

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get Default Branch
        id: get_branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep "HEAD branch" | cut -d ":" -f2 | tr -d ' ')
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Get Latest Tag
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "LATEST_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Update README Version
        run: |
          sed -i "s|implementation 'com.github.azzadpandit1122:AutoUpdateSdk:[^']*'|implementation 'com.github.azzadpandit1122:AutoUpdateSdk:${{ env.LATEST_TAG }}'|" README.md

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Update README to version ${{ env.LATEST_TAG }}"
          git push origin ${{ env.DEFAULT_BRANCH }}
